### ISSUE TITLE
Bone is already a framework

### ISSUE THREAD

**Issue by delboy1978uk** [liangjunmo/angemon#1]
Hello

Sorry to be the bearer of bad news, but I am the creator of Bone Framework, the first commit of which has been on Github since May 29, 2014. https://github.com/delboy1978uk/boneframework 

I kindly ask that you change the name of your Framework, and your namespaces.

Thanks
Derek Stephen McLean

**Comment by liangjunmo** [comment]
@delboy1978uk I got it, I have changed the framework name and namespace.

**Comment by delboy1978uk** [comment]
Wow, that was fast! Thank you so much for your cooperation and I wish you all the best and good luck with your framework. Have a great day! 😀
